Update pisos-monitor.yml

diff --git a/.github/workflows/pisos-monitor.yml b/.github/workflows/pisos-monitor.yml
--- a/.github/workflows/pisos-monitor.yml
+++ b/.github/workflows/pisos-monitor.yml
@@ -2,10 +2,7 @@ name: Pisos Monitor
 
 on:
   schedule:
-    # Executa cada 5 minuts
     - cron: '*/3 * * * *'
-  
-  # Execució manual amb paràmetres personalitzables
   workflow_dispatch:
     inputs:
       max_price:
@@ -37,6 +34,12 @@ jobs:
       uses: actions/setup-python@v4
       with:
         python-version: '3.11'
+    
+    - name: Debug files
+      run: |
+        pwd
+        ls -la
+        cat requirements.txt || echo "requirements.txt not found"
     
     - name: Install dependencies
       run: |
